examples/RobotFourDoor.jl, src/DataLayerAPI.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, src/SolveTree01.jl, src/SolverVisualization.jl, src/TreePotentials01.jl, test/runtests.jl
We can do considerably better using multiple dispatch, but this gets us going between Graphs.jl and CloudGraphs.jl. Currently using an API callback definition to point to necessary functions for general graph operations. @GearsAD
=> Change to getvertex via api

src/IncrementalInference.jl, src/SolveTree01.jl, test/testpartialconstraint.jl
towards predictive initialization of nodes
=> Refactored cliqGibbs product operations

REQUIRE, src/FGOSUtils.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, test/runtests.jl, test/saveconvertertypes.jl, test/testpartialconstraint.jl
fixes issue listed in JuliaLang/METADATA.jl#8448
=> Removetestingjldfile

src/FactorGraph01.jl
=> allow parallel factors by adding composition and f1

REQUIRE, src/ApproxConv.jl, src/SolveTree01.jl, src/SolverUtilities.jl, test/testGenericWrapParam.jl, test/testNumericRootGenericRandomized.jl
Fixes unanticipated API change `f!(x, F)` to `f!(F, x)` in NLsolve.jl.
cc @pkofod
=> fix nlsolve api changes

src/GraphConstraintTypes.jl
Although old types will be removed, this PR maintains consistency with Protobuf requirements for mutable structs.
=> factor types should be mutable

src/ApproxConv.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/IncrementalInference.jl, src/SolveTree01.jl
=> general maintenance and new eval feature

src/ApproxConv.jl, src/DispatchPackedConversions.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/SolverUtilities.jl, test/runtests.jl, test/testGenericWrapParam.jl, test/testMultithreaded.jl, test/testpartialconstraint.jl
Code can still be cleaned up in many ways, but this is PR is the first major conversion to multiprocess / mutlithreaded approximate convolutions and inference in IIF.  The code relies solely on new `CommonConvWrapper` fucntors.  This PR is intended strictly for `IIF v0.3.7+` and beyond.
fyi @mc2922, @GearsAD
=> multithreaded convolutions are working

src/FGOSUtils.jl, src/FactorGraph01.jl
cc @mc2922, fixing bug and default SingleThreaded.  Looks like there was an older issue from about 2 weeks ago that we all simply missed somehow...  Working on that now.  Has to do with inference over loadjld graphs.
=> SingleThreaded default with setThreadsAll fix

src/FactorGraph01.jl, src/JunctionTree.jl, src/SolveTree01.jl
almost `s:/print/info/g` and `s:/println/info/g`
=> ability to supress most printouts

src/FactorGraph01.jl, src/IncrementalInference.jl
Just checking what the changes were, dont merge yet
cc @pvazteixeira
=> old changes

src/FGOSUtils.jl, src/IncrementalInference.jl
=> add print graph max,

REQUIRE, src/SolverUtilities.jl, test/testCommonConvWrapper.jl, test/testNLsolve.jl
=> nlsolve(.., inplace=true)

src/FactorGraph01.jl
=> add warn for var duplication

Manifest.toml, Project.toml, REQUIRE, src/DefaultNodeTypes.jl, src/SerializingDistributions.jl, test/testmultihypothesisapi.jl
=> adding some docs

test/runtests.jl, test/testMultiHypo2Door.jl
=> new test 2 multihypo

src/SolveTree01.jl, test/testMultiHypo2Door.jl
Wasn't really an issue, but code is now more explicit.
=> fixes #251

.travis.yml, Manifest.toml, Project.toml, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, test/runtests.jl, test/serialization.jl, test/testCompareVariablesFactors.jl
IIF tests are passing with most of the code in tact.
=> Partial fix testing, JLD2 bypassed for now

src/FactorGraph01.jl, src/IncrementalInference.jl
=> some refactoring and cleanup

src/FactorGraph01.jl, src/JunctionTree.jl, test/unittests/FactorGraph01_tests.jl
=> Removing bayesnetvertid as it doesn't seem to be used

src/FactorGraph01.jl
=> add maxparallel to rmVarFromMarg

Project.toml, src/AliasScalarSampling.jl, src/CompareUtils.jl, src/Deprecated.jl, src/FGOSUtils.jl, src/IncrementalInference.jl
needs JuliaRobotics/DistributedFactorGraphs.jl#83
=> refactor fgos to dfg, fix bss,

src/AdditionalUtils.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/Deprecated.jl, src/FGOSUtils.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/SolveTree01.jl, src/SubGraphFunctions.jl, src/TreeBasedInitialization.jl
and many general fixes all round
=> down solve with frontal neighbors,

Project.toml, src/JunctionTreeTypes.jl
Only merge this when DFG 0.4 is tagged.
=> LightGraphDFG was renamed to MetaGraphDFG

Project.toml, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/FactorGraph01.jl, src/IncrementalInference.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/SubGraphFunctions.jl
- getEliminationOrder: uses getAdjacencyMatrixSparse 
- InMemDFGType set to DFG.GraphsDFG{SolverParams}
=> Cherrypick sparse getEliminationOrder and const InMemDFGType

src/ApproxConv.jl, src/CompareUtils.jl, src/Deprecated.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/InferDimensionUtils.jl, src/JunctionTree.jl, src/SolveTree01.jl, src/SolverUtilities.jl, src/SubGraphFunctions.jl, src/TreeBasedInitialization.jl, test/testExpandedJLD.jl, test/testFactorMetadata.jl, test/testgraphpackingconverters.jl, test/testmultihypothesisapi.jl, test/unittests/FactorGraph01_tests.jl
=> remove a few duplicate functions moved to DFG

src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/JunctionTree.jl, src/SolveTree01.jl, src/SubGraphFunctions.jl, src/TreeBasedInitialization.jl, test/testMultiHypo2Door.jl
tried to assign 1×100 array to 1×200 destination
=> Fix dimension error with N

src/JunctionTreeTypes.jl
=> Remove SymbolDFG and MetaGraphsDFG before DFG v0.5.0

src/CliqStateMachine.jl
fix #474 add csm edge from 7 to 10
=> fix csm for when parent marginalized

Project.toml, src/IncrementalInference.jl, src/JunctionTree.jl
#474, not fully fixed yet, but this will help find failure cases.
Also probably useful to know about this, @tonioteran
=> save variable order,

src/CliqStateMachine.jl, src/JunctionTree.jl, src/SolverAPI.jl, src/TreeBasedInitialization.jl
=> missing notification in parent recycling and pass variable order

src/IncrementalInference.jl, src/JunctionTree.jl, test/runtests.jl, test/testBasicCSM.jl, test/testCSMWithoutPriors.jl
cc @GearsAD -- #485, thanks!
Need to resolve tree case where leaves have not factors, as occurred here:
https://github.com/JuliaRobotics/IncrementalInference.jl/issues/485#issuecomment-566879819
=> new csm test, no prior,

src/JunctionTree.jl, src/JunctionTreeTypes.jl, test/testJunctionTree2.jl
=> add variable order to tree structure

src/CanonicalGraphExamples.jl, src/IncrementalInference.jl, src/JunctionTree.jl, test/runtests.jl, test/testTreeSaveLoad.jl
addresses #481 -- still WIP
cc @tonioteran -- you might be interested in these new functions.  Still need some work before its ready for general use.
=> add save load Tree,

src/SolverUtilities.jl, test/testCliqueFactors.jl
FYI @Affie , starting work on testing the second example from #458 , one task from #514
=> ex2 test from #458

.gitignore, src/AdditionalUtils.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/Deprecated.jl, src/DispatchPackedConversions.jl, src/FactorGraph01.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/InferDimensionUtils.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/SolveTree01.jl, src/SolverUtilities.jl, src/TreeBasedInitialization.jl, test/unittests/FactorGraph01_tests.jl
=> Towards breaking tree dependence on Graphs.jl

test/testBasicGraphs.jl
simplification related to #525
=> adjust test tolernance

src/SolveTree01.jl
=> bug fix for #530

.travis.yml, test/runtests.jl
=> attempt to fix #527

Project.toml, examples/TreeAnalysis.jl, src/AnalysisTools.jl, src/FactorGraph01.jl, src/IncrementalInference.jl, test/runtests.jl, test/testCcolamdOrdering.jl
=> make ccolamd usable,

src/IncrementalInference.jl
=> fix #489 spyCliqMat

src/CliqStateMachineUtils.jl
Related to https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/261
TODO:
- GraphsDFG
- LightDFG
- CloudDFG
- FuseDFG
- FileDFG
- GraffDFG
=> [BUGFIX] Sub-graph regression

Project.toml, src/CliqStateMachine.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, test/testCompareVariablesFactors.jl
=> add SolvedCount,

src/FactorGraph01.jl
quick refactor to remove deprecation warning.
=> Switch to current function version to remove deprecated warning (setSolverData!)

src/ApproxConv.jl, src/CliqStateMachine.jl, src/IncrementalInference.jl, src/SolveTree01.jl, src/SolverUtilities.jl, test/testProductReproducable.jl
still need to wire in the new test, with some work to first part of new test
=> maint and improvements

src/DefaultNodeTypes.jl, src/FactorGraph01.jl, src/Variables/Sphere1D.jl
=> remove labels 580

.travis.yml
=> only test arm64 on julia 1.3

.travis.yml
=> Test on DFG v0.6 tag

examples/ApproximateConvolution.jl, examples/IllustrateAutoInit.jl, examples/SquareRootTypes.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/DefaultNodeTypes.jl, src/Factors/Sphere1D.jl, src/GraphConstraintTypes.jl, src/SolverUtilities.jl, src/SubGraphFunctions.jl, src/TreeBasedInitialization.jl, test/testCommonConvWrapper.jl, test/testNLsolve.jl, test/testNumericRootGenericRandomized.jl, test/testmultihypothesisapi.jl, test/testpartialconstraint.jl
=> Factor <: Real and Abstracts

Project.toml, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/JunctionTree.jl, test/testJunctionTreeConstruction.jl
=> standard to graphinit,

src/DefaultNodeTypes.jl, test/runtests.jl, test/testMixturePrior.jl
=> fix and test MixturePrior,

Project.toml, src/CliqStateMachine.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/SolveTree01.jl, src/SolverAPI.jl, test/runtests.jl, test/testJunctionTreeConstruction.jl, test/testMultiHypo2Door.jl, test/testMultimodal1D.jl
also closes #617 
needs DFG v0.6.2
=> Fix 1D variable order regression, new test

.travis.yml, Project.toml, examples/BayesTreeIllustration.jl, src/DispatchPackedConversions.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/SolveTree01.jl, test/runtests.jl, test/testBasicGraphs.jl, test/testSaveLoadDFG.jl, test/testmultihypothesisapi.jl
Needs JuliaRobotics/DistributedFactorGraphs.jl#346
FIxes JuliaRobotics/DistributedFactorGraphs.jl#345
=> save multihypo to file

Project.toml, src/CliqStateMachineUtils.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl
=> renaming to biadjacency,

src/BeliefTypes.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/SolveTree01.jl, src/SolverUtilities.jl, src/TreeBasedInitialization.jl
=> drop TempBeliefMsg

src/ApproxConv.jl, src/DispatchPackedConversions.jl, src/ExplicitDiscreteMarginalizations.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/SolverUtilities.jl, test/testExplicitMultihypo.jl, test/testmultihypothesisapi.jl
=> add bad-init resolution for multihypo (#248)

src/ApproxConv.jl, src/FactorGraphTypes.jl, test/testBasicGraphs.jl, test/testMultimodal1D.jl
part of #237 and #248 , minor extension to #661 and #663
=> use spreadNH param

test/runtests.jl, test/testExplicitMultihypo.jl, test/testMultihypoAndChain.jl, test/testmultihypothesisapi.jl
=> add test from #462

src/BeliefTypes.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/Deprecated.jl, src/JunctionTreeTypes.jl, src/ParametricCliqStateMachine.jl, src/SolveTree01.jl, src/TreeBasedInitialization.jl, src/TreeMessageUtils.jl, test/testMixturePrior.jl
parht of #459, lots of small changes all over CSM and PCSM.  Work still ongoing.
=> WIP consolidating msg channels (#459)

src/SolveTree01.jl, src/SubGraphFunctions.jl
=> subgraph cleanup, bugfix,

src/Deprecated.jl, src/DispatchPackedConversions.jl
In support of JuliaRobotics/DistributedFactorGraphs.jl#433
=> refactor deprecate some packing,

src/DispatchPackedConversions.jl, src/IncrementalInference.jl
=> Also dispatch on solverData type for rebuildFactorMetadata!

src/CanonicalGraphExamples.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/JunctionTree.jl, src/ParametricCliqStateMachine.jl, src/ParametricUtils.jl, src/SubGraphFunctions.jl, test/testBasicParametric.jl, test/testSaveLoadDFG.jl, test/testgraphpackingconverters.jl
see [DFG#475](https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/475)
=> standardize to use solverParams and not params

src/FactorGraph.jl, src/FactorGraphTypes.jl, src/JunctionTree.jl, src/SolverAPI.jl, test/runtests.jl
usage ambiguity identified in #716
=> maxparallel -> SolverParams.maxincidence,

src/ApproxConv.jl, src/FactorGraph.jl, src/SolverUtilities.jl, test/testVariousNSolveSize.jl
=> update freshSample and N particles,

src/Deprecated.jl, src/JunctionTree.jl
=> address #678

src/BeliefTypes.jl, src/CliqStateMachine.jl, src/CliqStateMachine_Parametric.jl, src/JunctionTreeTypes.jl, src/SolveTree.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
see #744, part of #459 refactor
=> CliqStatus and initUpChannels

src/JunctionTreeTypes.jl, src/SolveTree.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl
=> BTND.initDownChannel::Channel{LikelihoodMessage}

src/BeliefTypes.jl, src/CliqStateMachine.jl, src/Deprecated.jl, src/JunctionTreeTypes.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
work in progress on #459, and partly resolves #674
=> prep to convert initupmsg to pull model

.travis.yml
=> Update travis - allow failures on ARM

src/CliqStateMachine.jl, src/Deprecated.jl, src/InferDimensionUtils.jl, src/JunctionTreeTypes.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
=> preliminary cleanup for dropping upinitmsg

src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/CliqStateMachine_Parametric.jl, src/Deprecated.jl, src/FactorGraph.jl, src/SolveTree.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
- part of #459 
- partially addresses #760
=> more cleanup prep before upinitmsg

Project.toml, src/CliqStateMachine.jl, src/TreeMessageUtils.jl
=> introduce CSM 8g.

src/CliqStateMachine.jl, src/TreeMessageAccessors.jl
=> fix csm 1. dfg, cleanup

src/CliqStateMachine.jl, src/CliqStateMachine_Parametric.jl, src/Deprecated.jl, src/IncrementalInference.jl, src/SolveTree.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
=> prep CSM before droping upInitMsg

Project.toml, src/CliqStateMachine.jl, src/CliqStateMachine_Parametric.jl, src/Deprecated.jl, src/JunctionTreeTypes.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl, test/testMixturePrior.jl, test/unittests/FactorGraph01_tests.jl
=> before dropping upInitChannel_

src/CliqStateMachine.jl, src/Deprecated.jl, src/JunctionTreeTypes.jl, src/SolveTree.jl, src/TreeBasedInitialization.jl, src/TreeMessageAccessors.jl
=> deprecate MsgUpInitChannel_

src/Deprecated.jl, src/JunctionTreeTypes.jl, src/TreeMessageAccessors.jl, src/TreeMessageUtils.jl
up part of #459 done.  Note testing in RoME continues to verify stability.
=> Up msg consolidation #459 done

Project.toml, examples/ApproximateConvolution.jl, examples/IllustrateAutoInit.jl, examples/SquareRootTypes.jl, src/ApproxConv.jl, src/CanonicalGraphExamples.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/CliqStateMachine_Parametric.jl, src/DeconvUtils.jl, src/DefaultNodeTypes.jl, src/Deprecated.jl, src/FGOSUtils.jl, src/FactorGraphTypes.jl, src/Factors/Sphere1D.jl, src/GraphConstraintTypes.jl, src/IncrementalInference.jl, src/SolverUtilities.jl, test/testCommonConvWrapper.jl, test/testNLsolve.jl, test/testNumericRootGenericRandomized.jl, test/testSaveLoadDFG.jl, test/testSpecialSampler.jl, test/testmultihypothesisapi.jl, test/testnullhypothesis.jl, test/testpartialconstraint.jl
Merge after https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/537
=> Renaming factor base types

src/CanonicalGraphExamples.jl, src/DefaultNodeTypes.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, test/testpartialconstraint.jl
See #783
Fixes for changes in softtype for [dfg #517](https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/517)
- ContinuousEuclid
- prep FactorMetadata
=> Updates towards stateless softtypes

src/DeconvUtils.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/IncrementalInference.jl, src/RequireInteractiveUtils.jl, test/testMultimodal1D.jl
partially addresses JuliaRobotics/DistributedFactorGraphs.jl#603
=> clean up addVariable!

src/FactorGraph.jl
removed in: https://github.com/JuliaRobotics/IncrementalInference.jl/pull/832
should close https://github.com/JuliaRobotics/RoME.jl/issues/324
=> Put back softtype (variableType) deprecations simplify addVariable!

src/CliqStateMachine.jl, src/TreeBasedInitialization.jl
=> Quiet buildSubraph with orphans

src/FactorGraph.jl, src/JunctionTree.jl
=> Tree building use @debug

src/DispatchPackedConversions.jl, src/FactorGraph.jl, test/testSaveLoadDFG.jl
=> fix rebuildFactorMetadata!

src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/Deprecated.jl, src/TreeBasedInitialization.jl, src/TreeMessageUtils.jl, src/TreeMsgDwnConsolidation.jl, test/testBasicTreeInit.jl
=> WIP 3 consolidate dwnMsg

src/CliqStateMachine_Parametric.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/SolveTree_Parametric.jl, src/SolverAPI.jl, test/testBasicParametric.jl
=> Parametric "take! and store" message again

Project.toml, src/CliqStateMachine.jl, src/FactorGraph.jl, src/SubGraphFunctions.jl, test/testBasicCSM.jl
=> warn_if_absent=false on update_!

src/TetherUtils.jl, test/runtests.jl, test/testDeadReckoningTether.jl
=> Test dead reckoning tether based on RoME test

examples/RobotFourDoor.jl
close #882
~~needs https://github.com/JuliaRobotics/RoMEPlotting.jl/pull/122~~
=> Fix RobotFourDoor example

src/CSMOccuranceUtils.jl, src/CliqStateMachine.jl, src/CliqStateMachineUtils.jl, src/TreeMessageAccessors.jl
=> double notify and CSMOccurance improvements

test/runtests.jl, test/testMixtureLinearConditional.jl
=> Simple MixtureLinearConditional test

src/BeliefTypes.jl, src/SolveTree.jl, src/SolverAPI.jl, src/TreeMessageUtils.jl, test/runtests.jl, test/testBasicGraphs.jl, test/testHasPriors913.jl
=> likelihood msgs do hasPriors

examples/BayesTreeIllustration.jl, examples/IllustrateAutoInit.jl
conflicts captured in #919 since the functions moved
=> latest example updates

src/TreeDebugTools.jl
=> changes from #918

src/Deprecated.jl, src/FGOSUtils.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl
part of but does not close #910
=> intermediate code refactor updates, towards #910

src/CSMCommon_Consolidate.jl, src/CliqStateMachineUtils.jl, src/CliqueStateMachine_fetch.jl, src/CliqueStateMachine_take.jl, src/Deprecated.jl, src/TreeMessageUtils.jl
=> Cleanup deleteMsgFactors!

src/CanonicalGraphExamples.jl, src/IncrementalInference.jl, src/SubGraphFunctions.jl, src/experimental/CliqStateMachine_X-stroke.jl, src/experimental/SolveTree_X.jl, test/runtests.jl, test/testExpXstroke.jl
- As separate functions for now, but can be integrated with existing take!. It is also reusing most of `fetch`'s important bits.
- It can only work with `useMsgLikelihoods`
=> take! mm tree init poc

src/TreeMessageUtils.jl
=> Use empty FG in addLikelihoodsDifferential!

src/CliqueStateMachine_fetch.jl
close #924
Tests:
- Passed RoME tests locally
- Passed with #957 also locally
=> Only downsolve when all children finished upsolve

Project.toml, src/CSMCommon_Consolidate.jl, src/CliqStateMachineUtils.jl, src/CliqueStateMachine_fetch.jl, src/IncrementalInference.jl, src/experimental/CliqStateMachine_X-stroke.jl
Consolidated with temporary functions:
`__doCliqUpSolveInitialized!`
`__doCliqDownSolve!`
=> Move code with __doCliqUpSolveInitialized! and __doCliqDownSolve!

src/CliqueStateMachine_fetch.jl, src/Deprecated.jl, src/TreeBasedInitialization.jl, src/experimental/CliqStateMachine_X-stroke.jl, test/runtests.jl, test/testInitVariableOrder.jl
=> getCliqVarInitOrderUp use subgraph

attic/CSMCommon_Consolidate.jl, src/CliqueStateMachine.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/ParametricCSMFunctions.jl, src/SolverAPI.jl, src/TreeDebugTools.jl, test/runtests.jl, test/testBasicTreeInit.jl, test/testSkipUpDown.jl
For #989
- Split out updateFromSubgraph_StateMachine
- Skip downsolve option + basic test
- Put back attemptTreeSimilarClique
- Bugfix printCliqHistorySequential
=> CSM updates

src/Variables/DefaultVariables.jl, src/Variables/Sphere1D.jl
=> Use @defVariable for Sphere1D and ContinuousScalar

examples/RobotFourDoor.jl
Hi @EstherVorkin
Here is a much updated example of FourDoor. Note that in our recent major overhaul of IncrementalInference.jl internals might present some teething problems.  We are working to tag IIF v0.17.0 in the next 10 days or so, which will present a much more stable workflow than previous versions.  We will make sure to update the unit tests to ensure this example is stable and works long term.  We had not been working with FourDoor in a very long time, apologies again for the delay.
Best,
Dehann
EDIT: 
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/b9d6dbd63557882e8a9955bb174da44c8b159150/examples/RobotFourDoor.jl#L1
=> fix #996, FourDoorExample.jl

src/CliqStateMachineUtils.jl, src/CliqueStateMachine.jl, test/testBasicTreeInit.jl
- Split down solve/init from postDown
- Split down solve/init from preDown
- renumber CSM
=> Split down CSM

src/DeconvUtils.jl
=> fix solveFactorMeasurements

src/JunctionTree.jl
=> User path in drawTree with spyCliqMat

src/CliqueTypes.jl, src/Deprecated.jl, src/JunctionTreeTypes.jl, src/TreeDebugTools.jl
Also cleanup
tree debugging bugfix
=> Set MetaBayesTree as default tree 

src/CliqueStateMachine.jl, src/JunctionTree.jl, src/SolverAPI.jl, test/runtests.jl, test/testTreeFunctions.jl
Bugfix: 
- getClique uses clique id
- UPRECYCLED -> draw orange
=> add `deleteClique!` function

src/CliqueStateMachine.jl, src/FactorGraphTypes.jl, src/JunctionTreeTypes.jl, test/testBasicTreeInit.jl
close https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1035
=> Limit treeinit iters with `limittreeinit_iters` and @error cleanly exit

src/TreeDebugTools.jl, test/testCSMMonitor.jl
=> CliqueId{Int64}.value on csm debug, and test

Project.toml, examples/TreeAnalysis.jl, src/AnalysisTools.jl, src/Deprecated.jl, src/FactorGraph.jl, src/IncrementalInference.jl, src/JunctionTree.jl, test/testAnalysisTools.jl, test/testBayesTreeiSAM2Example.jl, test/testCliqueFactors.jl, test/testJointEnforcement.jl, test/testJunctionTreeConstruction.jl, test/testMultimodal1D.jl
=> update tree API and IIF.isInitialized(::TreeClique)

.travis.yml, src/FactorGraph.jl, src/GraphProductOperations.jl, src/JunctionTree.jl, src/TreeDebugTools.jl
=> updates and maintenance to csm debugging tools 

src/ApproxConv.jl, src/Deprecated.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/IncrementalInference.jl, src/JunctionTree.jl, src/SolverUtilities.jl, src/TetherUtils.jl, test/testCommonConvWrapper.jl, test/testFactorMetadata.jl, test/testNLsolve.jl, test/testNumericRootGenericRandomized.jl
partially address #640, #927.  Stop empty constructor FactorMetadata()
=> refactoring fmd part 1,

src/Deprecated.jl, src/NumericalCalculations.jl, test/testpartialconstraint.jl
use `<:AbstractFactorMinimize` instead.  Towards #1072
=> remove partial Roots factor 

src/Deprecated.jl, src/NumericalCalculations.jl, test/testApproxConv.jl
=>  drop shuffleX, depr (::ccw)(x...)

src/ApproxConv.jl, src/Deprecated.jl, src/DispatchPackedConversions.jl, src/FactorGraphTypes.jl, src/NumericalCalculations.jl, src/SolverUtilities.jl, test/testFactorMetadata.jl, test/testMultihypoFMD.jl
towards #1025 #784 #825 #383
New code is still inefficient and requires refactoring of FMD.  Easier to do as part of CalcResidual work #467
=>  rm fmd fields, fix fmd multihypo

src/Deprecated.jl
=> add depr for fetchMsgUpThis

src/JunctionTree.jl, src/SolverAPI.jl
=> fix draw/show tree during solve,

attic/CSMCommon_Consolidate.jl, attic/CSM_SiblDwnInit_fetch.jl, src/CliqueStateMachine.jl, src/TreeMessageUtils.jl, test/testDefaultDeconv.jl
=> rn internal tags :__LIKELIHOOD...__

Project.toml, src/FactorGraph.jl, test/testmultihypothesisapi.jl
resolve #1086, back port of #1087
=> fix multihypo tolerance, needs backport

src/AdditionalUtils.jl, src/ApproxConv.jl, src/DeconvUtils.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/Factors/LinearRelative.jl, src/GraphProductOperations.jl, src/InferDimensionUtils.jl, src/JunctionTree.jl, src/NumericalCalculations.jl, src/SolverUtilities.jl, test/testDefaultDeconv.jl, test/testFactorMetadata.jl, test/testMixtureLinearConditional.jl, test/testSpecialSampler.jl, test/testmultihypothesisapi.jl
towards #825 and #467 and #927
=> _getCCW clean up and improvements

NEWS.md, src/ApproxConv.jl, src/CalcFactor.jl, src/DeconvUtils.jl, src/Deprecated.jl, src/FactorGraph.jl, src/Factors/DefaultPrior.jl, src/Factors/EuclidDistance.jl, src/Factors/LinearRelative.jl, src/Factors/Mixture.jl, src/Factors/Sphere1D.jl, src/NumericalCalculations.jl, src/SolverUtilities.jl, test/testCommonConvWrapper.jl, test/testHasPriors913.jl, test/testMixtureLinearConditional.jl, test/testMixturePrior.jl, test/testSpecialSampler.jl
towards closing #927 
aside #467
=> introduce `getSample(::CalcFactor, ::Int)`

Project.toml, src/CalcFactor.jl, src/Deprecated.jl, test/testApproxConv.jl
Better deprecation warning on `CalcFactor` changes
=> v0.20.2-rc1

src/TreeMessageUtils.jl
fix #1120 typename error, but tests still not passing
=> _findSubgraphsFactorType use nameof

test/testDefaultDeconv.jl
=> hotfix to restore tests

NEWS.md, Project.toml, src/Factors/EuclidDistance.jl, src/NumericalCalculations.jl, test/testpartialconstraint.jl
=> AbstractRelativeMinimize via residual

examples/ApproximateConvolution.jl, src/ApproxConv.jl, src/CalcFactor.jl, src/DeconvUtils.jl, src/Deprecated.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/IncrementalInference.jl, src/SolverUtilities.jl, test/testDERelative.jl, test/testMultihypoFMD.jl
=> rename freshSamples -> sampleFactor

src/ApproxConv.jl, src/DeconvUtils.jl, src/GraphProductOperations.jl, src/NumericalCalculations.jl, src/TetherUtils.jl
=> standardize numeric internals (towards #1010)

src/FactorGraphTypes.jl
towards fixing #467 
cc @Affie
=> CPT.res should not force type, use ::T instead

Project.toml, src/ApproxConv.jl, src/Deprecated.jl, src/GraphProductOperations.jl
=> simplify productpartials, AMP v0.1.5

src/NumericalCalculations.jl
I missed the dots. I kept missing it with CalcFactos also.
=> Update residual in _solveLambdaNumeric optim

src/ApproxConv.jl, src/IncrementalInference.jl, src/NumericalCalculations.jl, src/ParametricUtils.jl
=> update approxConvBinary getSample, import Optim

Project.toml, src/SolveTree.jl, src/SolverAPI.jl, test/testEuclidDistance.jl
xref 
- JuliaRobotics/RoME.jl#380 and 
- JuliaRobotics/RoME.jl#416
=> double direct during Gibbs

src/CanonicalGraphExamples.jl, test/testEuclidDistance.jl
@dehann, I just want to commit what I have so long on tests. I got a bit distracted with debugging and stripped out the test separately.
=> Euclid Distance fg generator and tests

src/JunctionTree.jl, src/JunctionTreeTypes.jl, test/testTreeFunctions.jl
=> ::TreeClique, Base.getindex, Base.show, ls

src/CliqueStateMachine.jl, src/Factors/MsgLikelihoods.jl, src/TreeMessageAccessors.jl, test/testTreeMessageUtils.jl
- close #1174
- fix compare likelihoodMessage bug
=> Add tree message getters

src/IncrementalInference.jl, src/SolverAPI.jl, test/runtests.jl, test/testCliqSolveDbgUtils.jl
=> add solveCliqUp! and api test

src/FactorGraphTypes.jl
@dehann, should we swop the default until #1010 is done?
=> Change default useMsgLikelihoods with warning

src/AdditionalUtils.jl, test/testBasicGraphs.jl
=> drawGraph allow relative path

Project.toml, src/AdditionalUtils.jl, src/BeliefTypes.jl, src/CompareUtils.jl, src/Deprecated.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/Factors/LinearRelative.jl, src/Factors/Sphere1D.jl, src/SerializingDistributions.jl, src/SolverUtilities.jl, src/TetherUtils.jl, test/testBasicTreeInit.jl
also 
- Towards #1010 
- JuliaRobotics/RoME.jl#244
- better replacement #1195
=> MKD replacement towards #1010, and

src/AliasScalarSampling.jl
=> Notes on 2D Alias sampling

src/SolverAPI.jl
=> Cleanup solveTree! internals

src/ApproxConv.jl, src/Deprecated.jl, src/FactorGraph.jl, src/NumericalCalculations.jl, src/ParametricUtils.jl, src/SolverUtilities.jl, src/TetherUtils.jl
=> towards #1246

examples/dev/testManiFactors.jl, src/ApproxConv.jl, src/FactorGraph.jl, src/Factors/GenericFunctions.jl, src/IncrementalInference.jl, src/NumericalCalculations.jl
=> update addEntropyOnManifoldHack! add AbstractManifoldMinimize

src/ApproxConv.jl, src/NumericalCalculations.jl, test/runtests.jl, test/testSpecialEuclidean2Mani.jl
needs https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/95
=> bugfix for ProductRepr and include SE(2) test

src/ApproxConv.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/NumericalCalculations.jl, test/testSpecialEuclidean2Mani.jl
`Vector{Any}` in `ccw` is the easiest way I can think of to fix this issue. 
I was thinking we get everything running again and then find a better solution 
The tests keep on failing on what looks like unrated numerical tests.
=> ccw points Any to fix mixed manifolds bug

src/Factors/GenericFunctions.jl, src/NumericalCalculations.jl, test/testSpecialEuclidean2Mani.jl
Hi @dehann, I just want to make sure `getManifold` on factors is the intended way to go
=> Use getManifold on factors

test/testSpecialEuclidean2Mani.jl
@dehann, I added this that was working prevoiusly. Perhaps you can look at it as part of your partials upgrade as it broke in the last week as far as I can tell.
=> Update SE2 manifold test with test_broken

Project.toml, examples/dev/factor_gradients.jl, src/ApproxConv.jl, src/CalcFactor.jl, src/Deprecated.jl, src/NumericalCalculations.jl, src/SolverUtilities.jl, test/runtests.jl
=> refactor calcFactorResidualTemporary, add _slack

NEWS.md, Project.toml, src/ApproxConv.jl, src/FactorGraph.jl, src/Factors/Circular.jl, src/Factors/DefaultPrior.jl, src/Factors/LinearRelative.jl, src/Factors/Mixture.jl, src/Factors/MsgLikelihoods.jl, src/IncrementalInference.jl, src/SolverUtilities.jl, src/services/FactorGradients.jl, test/testCommonConvWrapper.jl, test/testMixtureParametric.jl, test/testNumericRootGenericRandomized.jl, test/testSpecialEuclidean2Mani.jl, test/testSpecialOrthogonalMani.jl, test/testgraphpackingconverters.jl, test/testmultihypothesisapi.jl
needs JuliaRobotics/ApproxManifoldProducts.jl#120
cc @Affie
=> fix solveTree SE2

src/DeconvUtils.jl, src/NumericalCalculations.jl
IIF passes locally and RoME shows improvement. So I'm happy to merge.
=> Fix approxDeconv for manifold

Project.toml, src/ApproxConv.jl, src/CalcFactor.jl, src/CanonicalGraphExamples.jl, src/Deprecated.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/Factors/Mixture.jl, src/entities/FactorGradients.jl, src/entities/GraphConstraintTypes.jl, src/services/FactorGradients.jl, test/testFactorGradients.jl, test/testSpecialOrthogonalMani.jl, test/testpartialconstraint.jl
starting to add info per coord during convolutions, only Priors in this PR.  Prep for relatives which is coming soon.
=> conv belief partials on AbstractPrior

src/ApproxConv.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/entities/FactorGradients.jl, src/services/FactorGradients.jl, test/runtests.jl, test/testFactorGradients.jl, test/testGradientUtils.jl, test/testpartialconstraint.jl
Slowly working towards closing out #1010
=> wip toward ipc via perturbation on relative

src/services/FactorGradients.jl
ref https://github.com/JuliaRobotics/RoME.jl/pull/471#issuecomment-892770136
=> add AbstractManifoldMinimize to factor gradients

Project.toml, src/FactorGraph.jl, src/Factors/PartialPrior.jl, src/GraphProductOperations.jl, src/IncrementalInference.jl, src/services/ApproxConv.jl, src/services/GraphInit.jl, src/services/HeatmapSampler.jl, test/testBasicGraphs.jl, test/testPartialPrior.jl, test/testSpecialEuclidean2Mani.jl
WIP on demtest.jl not using Heatmap N for general products in graph, which is way to big and slow.
=> fix propagateBelief N, more testing, passThru fix

src/FGOSUtils.jl, src/FactorGraph.jl, src/Factors/EuclidDistance.jl, src/Factors/LinearRelative.jl, src/IncrementalInference.jl, src/ParametricUtils.jl, src/SolverUtilities.jl, src/entities/OptionalDensities.jl, src/entities/SolverParams.jl, src/services/ApproxConv.jl, test/testDeadReckoningTether.jl
This PR is about getting the generators in RoME running again.
Just note, we're still resolving Sphere(n) and earlier identity_element assumption.  Sphere(n) may work or break until JuliaRobotics/RoME.jl#465 is resolved.
=> Standardize to TranslationGroup

src/NumericalCalculations.jl, src/services/EvalFactor.jl, test/testSpecialEuclidean2Mani.jl, test/testTranslationMani.jl
=> fix calcVariableDistanceExpectedFractional

src/Factors/GenericFunctions.jl, src/IncrementalInference.jl, src/ManifoldSampling.jl, test/testSpecialEuclidean2Mani.jl, test/testSphereMani.jl, test/testTranslationMani.jl
oops should have changed the base branch back to master
=> Merge sampleTangent and samplePoint to master

src/Deprecated.jl, src/Factors/Circular.jl, src/Factors/GenericFunctions.jl, src/IncrementalInference.jl, src/ManifoldSampling.jl, src/SerializationMKD.jl, src/VariableStatistics.jl, src/Variables/DefaultVariables.jl, src/services/EvalFactor.jl, test/runtests.jl
I changed to RealCircularGroup as it was the closest to what we had and it works.
close #1365
This PR also looks at #150, but in IIF to use <:InferenceVariable
=> Update to  RealCircularGroup

src/GraphProductOperations.jl
xref JuliaRobotics/RoME.jl#504
=> simplify localProduct

Project.toml
PS, https://github.com/JuliaManifolds/Manifolds.jl/pull/427#issuecomment-923321936
=> bump Julia compat to 1.5

src/GraphProductOperations.jl, src/services/ApproxConv.jl, src/services/EvalFactor.jl, test/testpartialconstraint.jl
improvement but not full fix for #1394
xref #1010
=> better IPC on ARel partial, 

test/runtests.jl, test/testDefaultDeconv.jl
fixes #1482
also note new issue: 
- JuliaRobotics/FunctionalStateMachine.jl#46
=> unchecked timeout with no error msg

src/Factors/MsgPrior.jl, src/ParametricUtils.jl, src/TreeMessageUtils.jl, src/VariableStatistics.jl, src/entities/FactorOperationalMemory.jl
=> Towards fixing parametric

src/entities/JunctionTreeTypes.jl, test/testBasicRecycling.jl, test/testInitVariableOrder.jl
This passes on DFG master.
Perhaps the correct thing to do here is to manually force a variable ordering for these tests.
=> OrderedDict changed variable ordering

src/ExportAPI.jl, src/services/GraphInit.jl, test/testBasicGraphs.jl
=> makeSolverData!

.github/workflows/ci.yml
expecting ongoing issues with testMixtureParametric.  Recently found that test error, an will resolve separately.
=> add julia 1.9 to CI

src/entities/SolverParams.jl, src/services/FGOSUtils.jl
Needed for https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/1025
=> Support SolverParams in fileDFG and rm loadDFG

src/entities/CalcFactor.jl
we're probably not going for a dep warning as this was never released
=> rm getprop on cf.manifold
