JuliaRobotics/IncrementalInference.jl

src/FGOSUtils.jl, test/saveconvertertypes.jl
eliminates the need to overwrite these methods in other modules
as discussed at https://github.com/dehann/RoME.jl/commit/e564939b4db2bc02d26d5d9b21e2c338ec6815f4#commitcomment-21468647
=> Use getfield instead of eval for Packed type conversion

src/FactorGraph01.jl
=> fix issue #118

src/DispatchPackedConversions.jl
Fixes issue in categorical distribution parsing by normalizing categorical probabilities.
=> Renormalize categorical probabilities when parsing multi hypothesis factors

src/AliasScalarSampling.jl
Modified the normalization of weights to:
- remove negative values _before and after_ removing user-defined quantile
- normalize by `sum`
=> different weight normalization

src/IncrementalInference.jl, src/ccolamd.jl
adding the working module, but still need to wire the method to replace current variable ordering extraction using `qr permute` method.
=> start adding ccolamd work for manipulating variable ordering

Manifest.toml, Project.toml, src/JunctionTree.jl
This PR should address the API changes for DFG 0.1.4, where ls() and lsf() return `Vector{Symbols}` rather than `Vector{<:DFGNode}`.
There may be more changes required, but with this change batchSolve! can be run end-to-end on Hex example.
=> Updating API call for new signatures

examples/TexTreeIllustration.jl, src/JunctionTree.jl
Uses `dot2tex` python tool to generate a `.dot` and `.tex` representation of a Bayes (junction) tree from a `BayesTree` object.
=> Add generateTexTree function to produce Bayes tree with Tex labels.

src/BeliefTypes.jl, src/DefaultNodeTypes.jl, src/IncrementalInference.jl, src/ParametricCliqStateMachine.jl, src/ParametricUtils.jl, src/SubGraphFunctions.jl, src/TetherUtils.jl, src/TreeBasedInitialization.jl
=> basic solver

test/runtests.jl, test/testBasicForwardConvolve.jl
ensure #477
cc @nicrip, @pvazteixeira
=> add test to ensure approxConv for basic filter

src/JunctionTreeTypes.jl
Useful to debug stuck messages. 
Only Parametric and metagraphs supported so far
Needs consolidation from #558 to work on everything.
=> Draw edge colors based on messages, down:red, up:orange

src/BeliefTypes.jl, src/CliqueTypes.jl, src/IncrementalInference.jl, src/JunctionTreeTypes.jl
=> refactoring tree msg types (459)

src/FactorGraph.jl
On initialization, persist the values - these should be no-ops for in-memory.
=> Additional updates to persist the values on initialization

src/CliqStateMachine.jl, src/SubGraphFunctions.jl, src/TreeBasedInitialization.jl, test/testCompareVariablesFactors.jl
@dehann, we cannot have 2 defaults in the same API
Default is equivalent to old `getSubgraph`, with an optional distance it is equivalent to old `getSubgraphAroundNode`, also see [docs](https://juliarobotics.org/DistributedFactorGraphs.jl/latest/func_ref/#DistributedFactorGraphs.buildSubgraph-Union{Tuple{G},%20Tuple{Type{G},AbstractDFG,Array{Symbol,1}},%20Tuple{Type{G},AbstractDFG,Array{Symbol,1},Int64}}%20where%20G%3C:AbstractDFG)
=> Update to fit with DFG #459 fixes to buildSubgraph function

src/ApproxConv.jl, src/Deprecated.jl, src/FactorGraph.jl
fix #713
Still have to generalize for common nullhypo usage, but this is a step in the right direction.
=> add manifold and per particle nullhypo

src/TreeBasedInitialization.jl
relates to #852 .  Hi @Affie, think you misunderstanding whats happening here.  The design decision we all made was to keep DFGFactor immutable, but that means extracting a subgraph with only a list of variables must avoid orphaned factors -- the warning true by default is good enough to resolve that issue.  Lets please move on from this discussion, the subgraph consolidation is finalized for the foreseeable future.
=> remove misleading comment

src/TreeMessageUtils.jl, test/testDefaultDeconv.jl
fixes https://github.com/JuliaRobotics/IncrementalInference.jl/issues/913#issuecomment-699580458
```julia
using RoME
using RoMEPlotting
fg = generateCanonicalFG_Circle(6;graphinit=false)
fg.solverParams.useMsgLikelihoods = true
fg.solverParams.graphinit = false
fg.solverParams.treeinit = true
tree, smt, hist = solveTree!(fg)
p = RoMEPlotting.plotSLAM2D(fg)
```
=> Fix addLikelihoodsDifferential!

src/SolverAPI.jl
Enable clique history recording and provide smtasks, then retrieve with `fetchCliqHistoryAll!` even if an exception is thrown.
```julia
smtasks = Task[]
solveTree!(fg; smtasks, verbose=true, timeout=10, recordcliqs=ls(fg));
hists = fetchCliqHistoryAll!(smtasks);
```
=> Automatically store and retrieve history in task storage on dbg or rec

src/SolveTree_Parametric.jl, src/SolverAPI.jl
Also, check nothing in a failed task, prevent an error if you call `fetchCliqHistoryAll!` without recording cliques on a failed csm.
=> Update parametric with smtasks kwarg and bugfix

test/priorusetest.jl, test/runtests.jl
=> restore 458 461 test

src/JunctionTree.jl
xref #1015 , while deprecating Graphs.jl we'd like to avoid build new code requiring Graphs.jl.  We can revisit once Graphs.jl has been removed.
=> Removing bayes net draw while deprecating older Graphs.jl

src/AnalysisTools.jl, src/BeliefTypes.jl, src/Deprecated.jl, src/DispatchPackedConversions.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/GraphProductOperations.jl, src/InferDimensionUtils.jl, src/ParametricCSMFunctions.jl, src/ParametricUtils.jl, src/SolveTree.jl, src/TreeDebugTools.jl, src/TreeMessageUtils.jl, test/testgraphpackingconverters.jl
This PR 
- makes use of `getVariableType` from DFG instead of `getSofttype` and `.softtype`
- renames and deprecates `TreeBelief` field `softtype` for `variableType`
=> Rename softtype -> variableType, getSofttype -> getVariableType

src/CliqueStateMachine.jl, src/CliqueTypes.jl, src/CompareUtils.jl, src/Deprecated.jl, src/JunctionTree.jl, src/JunctionTreeTypes.jl, src/TreeMessageAccessors.jl, test/testSphere1.jl, test/testTreeFunctions.jl
- cleanup deprecated fields `parentCliq` `childCliqs` from `CliqStateMachineContainer`
- change `cliqKey::Int` to  `cliqId::CliqueId{Int}` in `CliqStateMachineContainer`
- remove unused `TreeClique` label field 
This PR is towards having the Tree independent of the underlying graph technology as with DFG.
The idea is that CliqueId is the unique field as per #540
=> Allow dispatch on cliq id vs graph index by using CliqueId

src/Factors/LinearRelative.jl, src/Factors/Mixture.jl, src/NumericalCalculations.jl, test/testMixtureLinearConditional.jl, test/testMixturePrior.jl
Small breaking change where `getSample(::Mixture...)` no longer returns the selected component labels as second element in tuple.  See #1099 for more details.
=> first test pass on CalcFactor (LinearRelative)

.github/workflows/ci.yml
For good example, also see:
https://github.com/mcabbott/Tullio.jl/blob/master/.github/workflows/ci.yml
All this already working on Travis, but new pricing driving us towards Github Actions instead:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/master/.travis.yml
Must do similar for:
=> Switch to Github CI

src/FactorGraph.jl, src/ParametricUtils.jl, src/SolverAPI.jl, test/testBasicParametric.jl
A step towards consolidation creates residual using `eltype` of variable[1]. 
residual not buffered though, but not to bad.
=> Parametric getParametricMeasurement and CalcFactorMahalanobis

NEWS.md, examples/ApproximateConvolution.jl, examples/SquareRootTypes.jl, src/CalcFactor.jl, src/DeconvUtils.jl, src/Factors/DefaultPrior.jl, src/Factors/EuclidDistance.jl, src/Factors/LinearRelative.jl, src/Factors/MsgLikelihoods.jl, src/Factors/Sphere1D.jl, src/NumericalCalculations.jl, src/ODE/DERelative.jl, src/ParametricUtils.jl, test/testCSMMonitor.jl, test/testCommonConvWrapper.jl, test/testDeadReckoningTether.jl, test/testMultihypoFMD.jl, test/testNumericRootGenericRandomized.jl, test/testSpecialSampler.jl, test/testmultihypothesisapi.jl, test/testpartialconstraint.jl
=> Return Residual in CalcFactor

src/ApproxConv.jl, src/CalcFactor.jl, src/FactorGraphTypes.jl, src/TetherUtils.jl
=> Improve types on CCW and CPT

Project.toml, src/Deprecated.jl, src/Factors/MsgLikelihoods.jl, src/TreeMessageUtils.jl, test/runtests.jl, test/testTreeMessageUtils.jl
Needed for https://github.com/JuliaRobotics/RoMEPlotting.jl/pull/151
Repeating here: I changed the broken belief message `TempUpMsgPlotting` in IIF to a named tuple,  I see it as a bug fix and not a breaking change since it's been broken for a while. RoMEPlotting will need v0.21.1 compact to use `plotCliqUpMsgs` again.
Changes:
- stackCliqUpMsgsByVariable
- getTreeCliqUpMsgsAll
- UpMsgPlotting
TODO
=> Fixes for plotCliqUpMsgs

src/CliqueStateMachine.jl, src/JunctionTree.jl, src/ParametricUtils.jl, src/SolverAPI.jl, test/testEuclidDistance.jl
Hi @dehann, I don't know if this is what you had in mind for `solveCliqu!` from #1168. 
I didn't know exactly what we wanted to do with solveCliq!. Problem was: It is still solving as if its part of the larger tree, so it's trying to access messages from the rest of the tree. It's easy to add the channels for the messages but then it would just block on them waiting. So where should these messages come from?
For this PR I went with solving the clique in isolation, it doesn't make sense if its not a leave clique though.
=> solveCliq! in isolation

NEWS.md, Project.toml, src/FGOSUtils.jl, src/FactorGraph.jl, src/Factors/EuclidDistance.jl, src/Factors/LinearRelative.jl, src/GraphProductOperations.jl, src/IncrementalInference.jl, src/NeedsResolution.jl, src/ParametricUtils.jl, src/SubGraphFunctions.jl, src/Variables/DefaultVariables.jl, test/testBasicGraphs.jl, test/testBasicParametric.jl, test/testDeadReckoningTether.jl
Only use `getManifold` instead.  Also completely dropping `getDomain`.
relates to 
- #1010,
- #1141,
- JuliaRobotics/RoME.jl#244
=> drop use of getManifolds

.github/workflows/ci.yml
Following strategy from JuliaRobotics/ApproxManifoldProducts.jl#82
=> TRy fix JULIA_PKG_SERVER=""

examples/dev/factors_sandbox.jl, examples/dev/testManiFactors.jl, src/ApproxConv.jl, src/CompareUtils.jl, src/FGOSUtils.jl, src/FactorGraph.jl, src/FactorGraphTypes.jl, src/Factors/GenericFunctions.jl, src/NumericalCalculations.jl, src/ParametricUtils.jl, test/runtests.jl, test/testMixtureLinearConditional.jl, test/testSpecialOrthogonalMani.jl, test/testSphereMani.jl
- Factors returns tangent vector at p
- _solveLambdaNumeric does distance2
- parametric does Mahalanobis distance2
Tests added:
- @test_broken that fails on Sphere(2) - #1293
- test on SO(2)
- test on SO(3)
Needs:
- https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/94
- ~~https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/788~~
- we are storing coordinates for now
Breaks (TODO):
- ~~Maybe CCW serialization~~ - slightly related to https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/590#issuecomment-776838053
- Skips compare on `vartypes` field in ccw. captured in https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/434
- ~~Parametric~~
=> WIP on manifold optimization and factors

NEWS.md, Project.toml, examples/dev/factor_gradients.jl, src/ApproxConv.jl, src/CalcFactor.jl, src/Deprecated.jl, src/FGOSUtils.jl, test/testSpecialOrthogonalMani.jl
HI @Affie , see the start of a crude-memory jacobian calculator for factor residuals (in coordinates).  I was thinking of making this a functor to improve in-place operations, but that would be a later optimization. What I'd like to do here is via many lambdas create a constructor for say `struct FactorJacobian` which generates all the necessary numerical lambdas during construction, but can then calculate more quickly calculate the gradients when needed.  For example, something to the effect of:
```julia
pp = Pose2Pose2(...)
jacobian_functor = IIF.FactorJacobian(pp, Pose2, Pose2)
_J = zeros(6,6)
jacobian_functor(J_, z, p1, p2) # doing inplace operations on `J_` based on current values in `z,p1,p2`
@show _J
jacobian_functor(J_, z, p3, p4)
```
This is still the jacobian relative to …
=> improve API, towards infoPerCoord

Project.toml, src/DispatchPackedConversions.jl, src/IncrementalInference.jl, src/SerializationMKD.jl, test/testMixtureLinearConditional.jl, test/testgraphpackingconverters.jl
also fixes tests, and xref:
- JuliaRobotics/ApproxManifoldProducts.jl#116
- JuliaRobotics/DistributedFactorGraphs.jl#590
=> move MKD serialization downstream to IIF

src/Factors/GenericFunctions.jl, src/NumericalCalculations.jl
Perhaps just temporary to make factors like BearingRange easier.
=> Manifold factors change to return coordinates

src/IncrementalInference.jl
This is needed to support getFactor() for DFG types that use NoSolverParams.
=> Adding getFactorOperationalMemoryType for NoSolverParams

src/TetherUtils.jl, src/services/ApproxConv.jl, test/testDeadReckoningTether.jl
xref design decision (w @Affie) for `getMeasurementParametric` to always return coordinates (`::Vector{Float64}`).
xref JuliaRobotics/RoME.jl#465
=> fix solveFactorParametric as coordinates only

src/Factors/GenericFunctions.jl, src/IncrementalInference.jl, src/ManifoldSampling.jl, test/testSpecialEuclidean2Mani.jl, test/testSphereMani.jl
In place of https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/152
from https://github.com/JuliaRobotics/RoME.jl/issues/465
getSample for factors will then use this pattern:
```julia
function getSample(cf::CalcFactor{<:Pose2Pose2}, N::Int=1) 
M = getManifold(Pose2)
ϵ = getPointIdentity(Pose2)
X = [sampleTangent(M, cf.factor.z, ϵ) for _=1:N] 
return (X, )
end
```
=> `sampleTangent` and `samplePoint` 

src/services/EvalFactor.jl, test/testPartialPrior.jl, test/testSpecialEuclidean2Mani.jl
So far only tested with Partial Pose3 https://github.com/JuliaRobotics/RoME.jl/pull/495 but numerics fail
Updated PartialDim2{T} <: AbstractPrior to use getManifold method, while PartialPrior falls back to using getManifoldPartial
Just note that I do not know what to do with factors like `PartialPrior` that do not have a manifold assigned. I think it would be best to have all factors assigned a Manifold with Euclidean/TranslationGroup for the current linear ones.
=> Try getManifold fall back to getManifoldPartial to get the manifold used in partial priors

src/DeconvUtils.jl, src/NumericalCalculations.jl, src/services/CalcFactor.jl, test/testSpecialEuclidean2Mani.jl
close #1374
Note: only for measurements as tangent vectors
=> Fix and test manifold approxDeconv

src/DeconvUtils.jl, src/IncrementalInference.jl, src/TreeMessageUtils.jl
a change that came as part of Manifolds.jl upgrade.  This PR restricts to only Lie group manifolds, but advances differential factors to use new approxDeconv which now returns tangents (previously was always assumed just to be tangents).  Relaxing the Lie group assumption should happen along with #1010 
Closes #1386
=> differential factors from deconv tangents to points

src/Deprecated.jl, src/ExportAPI.jl, src/Factors/Circular.jl, src/Factors/DefaultPrior.jl, src/Factors/EuclidDistance.jl, src/Factors/GenericFunctions.jl, src/Factors/GenericMarginal.jl, src/Factors/LinearRelative.jl, src/Factors/Mixture.jl, src/Factors/MsgPrior.jl, src/Factors/PartialPrior.jl, src/Factors/PartialPriorPassThrough.jl, src/Serialization/entities/AdditionalDensities.jl, src/Serialization/entities/FluxModelsSerialization.jl, src/Serialization/services/FluxModelsSerialization.jl, src/Serialization/services/SerializingDistributions.jl, test/testCircular.jl, test/testFluxModelsDistribution.jl, test/testHeatmapGridDensity.jl, test/testmultihypothesisapi.jl
needs JuliaRobotics/DistributedFactorGraphs.jl#848
EDIT: local tests are passing with correct DFG branch.
----
small improvement towards reducing workload on JuliaRobotics/DistributedFactorGraphs.jl#590
=> packed factors are nested JSON only,

src/services/EvalFactor.jl
this is a workaround, deferring proper fix as part of #1492 
This workaround keeps fuzzy whether partial factor manifolds should be full dimension from one of the associated variables, or restricted to only the dimensions in question.  E.g. what manifold should this return: `getManifold(Pose2Point2BearingRange)` -- `SE(2)`, `Translation(2)`?
=> workaround for partials, xref #1492

src/services/EvalFactor.jl, test/testEuclidDistance.jl
Basically the same test that fails in https://github.com/JuliaRobotics/RoME.jl/issues/618
=> Test Point2Point2Range as in RoME

src/entities/FactorOperationalMemory.jl, src/services/CalcFactor.jl, src/services/DeconvUtils.jl, src/services/EvalFactor.jl, src/services/NumericalCalculations.jl, test/testMultithreaded.jl
=> Remove CPT

Project.toml, src/ConsolidateParametricRelatives.jl, src/Deprecated.jl, src/Factors/Circular.jl, src/ManifoldsExtentions.jl, src/ParametricUtils.jl, src/Variables/DefaultVariables.jl, src/services/EvalFactor.jl, src/services/FGOSUtils.jl, src/services/NumericalCalculations.jl, test/testSpecialEuclidean2Mani.jl
HeatmapSampler test fails repeatedly on github ci, but passes locally. So skipping in this pr with a new issue to fix the test
- see issue #1714
=> Change points to StaticArrays

src/Factors/Mixture.jl, src/entities/CalcFactor.jl, src/services/CalcFactor.jl, src/services/DeconvUtils.jl, src/services/EvalFactor.jl, src/services/NumericalCalculations.jl, test/testSpecialEuclidean2Mani.jl
~~This only focused on hex (pose2 and point2) a lot of other things are untested and likely broken.~~
Tests are looking ok.
This also fixes a deconv issue where the variable manifold was used instead of the factor manifold. and close #1785
=> Use CalcFactorNormSq as functor
